name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar diariamente
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install axios

      - name: Ejecutar el script para actualizar el README
        run: node scripts/update-readme.js

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Actualizar estadísticas del README automáticamente"
          git push origin develop
